### PR TITLE
Updates react to version 0.10.0.

### PR DESCRIPTION
**Pull request by adri**
The update would be great because other libraries use the 0.10.0 as well.

I tried to run the tests but for me some `test:console` fail with either version with `ReferenceError: document is not defined`. `test:web` runs fine.

Do you have the same?

```
./node_modules/gulp/bin/gulp.js test:console

[15:14:11] Using gulpfile /Users/adri/workspace/react-topcoat/gulpfile.js
[15:14:11] Starting 'build:src'...
[15:14:11] Finished 'build:src' after 149 ms
[15:14:11] Starting 'test:console'...
[15:14:13] Finished 'test:console' after 1.58 s
6 passing (11ms)
  3 failing

  1) Button with variant cta "before each" hook:
     ReferenceError: document is not defined
    at Object.ReactTestUtils.renderIntoDocument (/Users/adri/workspace/react-topcoat/node_modules/react/lib/ReactTestUtils.js:51:15)
    at Context.<anonymous> (/Users/adri/workspace/react-topcoat/build/js/topcoat/button_spec.js:25:22)
    at Hook.Runnable.run (/Users/adri/workspace/react-topcoat/node_modules/mocha/lib/runnable.js:221:32)
    at next (/Users/adri/workspace/react-topcoat/node_modules/mocha/lib/runner.js:259:10)
    at Object._onImmediate (/Users/adri/workspace/react-topcoat/node_modules/mocha/lib/runner.js:276:5)
    at processImmediate [as _immediateCallback] (timers.js:336:15)


  2) Button with variant quiet "before each" hook:
     ReferenceError: document is not defined
    at Object.ReactTestUtils.renderIntoDocument (/Users/adri/workspace/react-topcoat/node_modules/react/lib/ReactTestUtils.js:51:15)
    at Context.<anonymous> (/Users/adri/workspace/react-topcoat/build/js/topcoat/button_spec.js:41:22)
    at Hook.Runnable.run (/Users/adri/workspace/react-topcoat/node_modules/mocha/lib/runnable.js:221:32)
    at next (/Users/adri/workspace/react-topcoat/node_modules/mocha/lib/runner.js:259:10)
    at Object._onImmediate (/Users/adri/workspace/react-topcoat/node_modules/mocha/lib/runner.js:276:5)
    at processImmediate [as _immediateCallback] (timers.js:336:15)


  3) Button when large "before each" hook:
     ReferenceError: document is not defined
    at Object.ReactTestUtils.renderIntoDocument (/Users/adri/workspace/react-topcoat/node_modules/react/lib/ReactTestUtils.js:51:15)
    at Context.<anonymous> (/Users/adri/workspace/react-topcoat/build/js/topcoat/button_spec.js:57:22)
    at Hook.Runnable.run (/Users/adri/workspace/react-topcoat/node_modules/mocha/lib/runnable.js:221:32)
    at next (/Users/adri/workspace/react-topcoat/node_modules/mocha/lib/runner.js:259:10)
    at Object._onImmediate (/Users/adri/workspace/react-topcoat/node_modules/mocha/lib/runner.js:276:5)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

### CODE REVIEW

**Comment by plaxdan** [comment]
Thanks for the update. Yes `test:console` fails because I haven't added a headless browser to the tests yet (such as [PhantomJS](http://phantomjs.org/) or [jsdom](https://github.com/tmpvar/jsdom)). Without something like these there is no global `document` object. In the browser there is such a global object so the tests run fine.

p.s. at the [suggestion of one of the members](https://github.com/topcoat/topcoat/issues/486#issuecomment-37240241) of the Topcoat team I've begun to split the components out into separate packages (e.g. [topcoat-button-react](https://github.com/plaxdan/topcoat-button-react))

**Comment by adri** [comment]
I like the idea of separating the components very much!
How do you include the actual css? Right now i require the needed css by stylus `require` statements for the components which are needed. I wonder if there might be a better way to handle the css 'attached' to a component.

**Comment by plaxdan** [comment]
I am switching to webpack http://webpack.github.io/ which allows you to
require css just like you'd require any other javascript file. Someone
requiring the topcoat react component would then get all the css and any
other images / fonts etc for free.

Just have to find the time to get it done :)

**Comment by adri** [comment]
Hmm very nice idea!

So then the users of the react-topcoat library need to use webpack too, right?
Maybe a check if webpack is running could handle the case if someone is not using webpack.

I’m actually using webpack, maybe I can take a look as well but it’s not a prio right now ;-)

**Comment by plaxdan** [comment]
No users of the lib would just need to require the lib. Webpack is only
needed for people that want to build the lib from source.

When publishing the lib to NPM we'd either include a pre-webpacked src and
point to that as the [main](https://www.npmjs.org/doc/package.json.html#main) inside
the package.json or we could specify that the code is built from src on
[preinstall](https://www.npmjs.org/doc/misc/npm-scripts.html) (in which case
they would need a local webpack) but that would be in devDependencies and
therefore downloaded automatically so they wouldn't need to explicitly
install or even know about webpack.

**Pull request merged**
